= Исправление доступности операции редактирования маршрута в карточке согласования КС

.Разрешите операцию "Кнопки редактирования маршрута" в "Конструкторе состояний":
. Откройте _Конструктор состояний_.
. Выберите вид _Согласование КС_.
. Разрешить операцию _Кнопки редактирования маршрута_ в состояниях _Подготавливается_, _Запущено_ и _Приостановлено_.
. Сохраните.

[start=5]
.Разрешите операцию "Кнопки редактирования маршрута" в "Конструкторе ролей":
. Откройте _Конструктор ролей_.
. Выберите вид _Согласование КС_.
. Разрешите роли _Инициатор_ операцию _Кнопки редактирования маршрута_ для состояний _Подготавливается_, _Запущено_ и _Приостановлено_.
. Сохраните.

[start=9]
.Привяжите операцию "Кнопки редактирования маршрута" к элементу управления "Редактор этапов":
. Откройте _Конструктор разметок_.
. Выберите вид _Согласование КС_.
. Откройте разметку _Инициатор управление_.
. В настройках элемента управления _Редактор этапов_ (вкладка _Состав маршрута_) укажите операцию редактирования -- _Кнопки редактирования маршрута_.
. Повторите привязку операции редактирования для разметки _Инициатор подготовка_.
. Сохраните.
