= Ключевые изменения в версии 6.1

{pl} {dv} 5.4 представляла собой монолит, который включал сервер и клиент {dv}, модули {ad}, {dm}, {bo} и т.д. Дополнительные модули и Приложения устанавливались отдельно.

.В {dv} 6.1 данный монолит разделён на отдельные модули:
* {pl}.
* {bo}.
* {dm}.
* {wf}.
* {ad}.
* {wincl}.
* {to}.
* Появилось требование установки: _Службы {ws}_, _{of-sett-serv}_, _Сервиса внешнего API {of-mc}_, _{of-mc}_.
* При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется отдельными командами.
* В {dv} 6.1 модули обладают пакетами установки на Linux и пакетами установки .msi для установки на Windows, а также комплектом документации.
+
Временное ограничение, требующее установки серверных компонентов модулей из инсталляторов `.msi` на машину с ОС Windows обусловлено необходимостью работы с Консолью настройки {dv} и настройкой БД. Подробнее про имеющиеся ограничения можно прочитать в руководстве по установке системы, раздел "xref:install-linux::linux-limitations.adoc[]".

== Сателлитные базы данных

В новой версии появилась возможность использовать отдельные базы данных для хранения архивных карточек, журналов и некоторых системных таблиц.

== Поддержка внешних хранилищ файлов

В {dv} 6.1 содержимое файлов может быть вытеснено из основной БД {dv} в отдельную БД, на файловую систему или в иное хранилище.

== Поддержка СУБД PostgreSQL

В качестве СУБД теперь может использоваться PostgreSQL, подробнее см. "xref:platform:console:appendix/microsoft-postgre.adoc[]".

== Хранение расширенных метаданных в БД

.В новой версии изменился способ хранения расширенных метаданных в БД:
* Поля сохраняются в основных таблицах секций. Раньше использовались extended-секции.
* Для секций создаются таблицы со стандартными секционными названиями -- без суффикса *_extended*.

Данное изменение не затрагивает способ хранения динамических метаданных.

== Обновления модулей без полного обновления БД

Реализован механизм обновления базовых модулей {dv} ({pl}, {bo} и др.), значительно ускоряющий процесс обновления БД. Если у модуля изменились только программные компоненты, но не изменилась библиотека карточек, при его обновлении библиотека карточек повторно загружаться не будет.
