= Условия обновления

== Возможность обновления

До версии {dv} 5.5 может быть обновлена система {dv} версии 5.4.2642 (без ограничений).

WARNING: Обновление {dv} 4.5 до версии 5.5 не поддерживается.

== Системные требования

В {dv} 5.5 изменились требования к компьютерам, на которые устанавливаются серверные и клиентские части модулей. Системные требования приведены в руководствах администратора модулей {dv}, а также в инструкции по установке {dv}.

.Важные изменения:
[WARNING]
====
* Сервер {dv} больше не поддерживает установку на компьютер с 32-разрядной операционной системой.
* Для СУБД Microsoft SQL Server обязательным компонентом стала _Служба агента SQL Server_ (_SQL Server Agent_).
====

== Предварительная проверка обновления

Перед обновлением рабочего сервера {dv} рекомендуется опробовать обновление на тестовом сервере *с актуальной копией рабочей базы данных*.

Рабочий сервер следует обновлять только убедившись, что обновление тестового сервера прошло корректно и выполняются стандартные сценарии работы пользователей в {dv}.

== Работа с {dv} во время обновления

Работа с системой {dv} во время обновления будет невозможна.

Доступ пользователей и сервисов в {dv} должен быть закрыт.
