= Удаление {dv} 5.4

. Удалите программу _{dv} 5 Client_ с пользовательских компьютеров стандартным образом (используя меню Установка и удаление программ).
+
После удаления убедитесь, что был очищен каталог установки программы, и в GAC компьютера отсутствуют библиотеки {dv}.
+
. Перезагрузите компьютер.
+
. Удалите все установки сервера {dv} стандартным образом.
+
Перед удалением сохраните настройки сервера (названия подключенных баз данных, учетные записи сервисов, имена почтовых профилей, настройки производительности сервиса Workflow, и другие), которые можно найти в Консоли настройки {dv}.
+
При удалении сервера {dv} на запрос удаления настроек ответьте утвердительно.
+
После удаления убедитесь, что был очищен каталог установки программы, и в GAC компьютера отсутствуют библиотеки {dv}.
+
. Перезагрузите компьютер.
+
. Если был отдельно установлен СУБП (Workflow), удалите их стандартным образом.
+
После удаления убедитесь, что был очищен каталог установки программы, и в GAC компьютера отсутствуют библиотеки {dv}.
+
. Перезагрузите компьютер.
+
. Если был отдельно установлен сервис полнотекстового поиска, удалите его стандартным образом.
+
После удаления убедитесь, что был очищен каталог установки программы, и в GAC компьютера отсутствуют библиотеки {dv}.
+
. Перезагрузите компьютер.
