= Действия после установки обновления

[#components]
== Обновление компонентов собственных библиотек карточек

В новой версии модуля {pl} изменился механизм проверки соответствия клиентских компонентов библиотек карточек (см. xref:6.1@platform:common:change-log.adoc[список изменений] модуля {pl}).

.Если в решении на базе {dv} реализованы собственные библиотеки карточек:
. Подключите новые сборки {dv} к проекту компонента.
. Добавьте в ресурсы XML-файл с описанием библиотеки карточек.
. В реализацию класса `CardLibrary` -- если .NET-сборка -- добавить переопределение метода `GetLibraryDefinition`. Метод должен возвращать описание библиотеки карточек.
+
[sorce,csharp]
----
protected override string GetLibraryDefinition()
{
  return Resources.CardLibDefinition;
}
----
+
. Повторно соберите, протестируйте работоспособность и распространите клиентский компонент библиотеки карточек.
+
.Для С++ реализации клиентского компонента библиотеки карточек нужно:
* Поддержать интерфейс `ICardLibraryInfo2`;
* Изменить поведение свойства `ICardLibraryInfo.Version`.
+
См. подробнее в руководстве разработчика, раздел "xref:programmer:samples:solution/snap-in/new-snap-in.adoc[]").

include::partial$console.adoc[]
