= Выбор маршрута согласования в зависимости от атрибутов документа

.Добавьте элемент управления "Маршруты согласования по условию" в разметку вида "Согласование КС":
. Откройте _Конструктор разметок_.
. Выберите вид _Согласование КС_.
. Откройте разметку _Настройка_.
. Измените текст метки у элемента управления `_Маршрут_` (выбор маршрута согласования) на _Маршрут согласования по умолчанию_.
. Перетащите элемент управления `_Маршруты согласования по условию_` с панели инструментов на разметку.
. Измените название добавленного элемента управления на _PathList_. Также измените текст метки у данного элемента, используя значение _Маршруты согласования по условию_.
. Сохраните.

[start=8]
.Измените обработчик события сохранения карточки:
. Откройте _Конструктор скриптов_.
. Выберите вид _Согласование КС_.
. Переопределите метод `CardSaving`, добавив код:
+
[source,csharp]
----
public override void CardSaving(System.ComponentModel.CancelEventArgs e)
{
    base.CardSaving(e);
    if (!e.Cancel)
        ReconcileScript.CardSaving(e);
}
----
+
. Скомпилируйте скрипт и сохраните.