= Выбор маршрута согласования в зависимости от атрибутов документа

. Добавьте элемент управления “Маршруты согласования по условию” в разметку вида _Согласование КС_:

. Откройте _Конструктор разметок_.

. Выберите вид _Согласование КС_.
. Откройте разметку “Настройка”.
. Измените текст метки у элемента управления “Маршрут” (выбор маршрута согласования) на “Маршрут согласования по умолчанию”.
. Перетащите элемент управления “Маршруты согласования по условию” с панели инструментов на разметку.
. Измените название добавленного элемента управления на “PathList”. Также измените текст метки у данного элемента, используя значение “Маршруты согласования по условию”.
. Сохраните.
. Измените обработчик события сохранения карточки:

. Откройте _Конструктор скриптов_.

. Выберите вид _Согласование КС_.

. Переопределите метод `CardSaving`, добавив код:

`csharp
  public override void CardSaving(System.ComponentModel.CancelEventArgs e)
  {
      base.CardSaving(e);
      if (!e.Cancel)
          ReconcileScript.CardSaving(e);
  }
`

. Скомпилируйте скрипт и сохраните.