= Отображение делегатов в элементе управления "Дерево исполнения"

. Открыть Конструктор разметок, выбрать тип карточек _Задание_, вид -- _На исполнение_ (подвид _Задание УД_).

. Поочерёдно в разметках _Контроль_, _Завершено_ и _Исполнение_ на вкладке _Дерево исполнения_ в свойствах элемента управления _Дерево исполнения_ в группе Поведение/Столбцы установить флаг для значения _Делегировал_.

. Выполнить сохранение Конструктора разметок.

. Для вида задания _На ознакомление_ настройка выполняется аналогичным образом, необходимо повторить шаги 1-3.

. Для всех видов, дочерних к _Задание КС_, шаги 1-3 выполняется для разметок _Базовая_ и _Делегирование_.

. Для видов карточек _Группа заданий_ и _Группа заданий УД_ дополнительные настройки не требуются, столбец _Делегировал_ появляется автоматически на вкладке _Задания_.

. Для вида _Согласование КС_ карточек типа _Согласование_ необходимо выполнить шаги 1-3 для разметки _Инициатор управление_, выполнив указанные действия для элемента управления, расположенного на вкладке _Задания_.

. Во всех документах УД шаги 1-3 выполняются на вкладке _Задания_.