= Завершение этапов согласования в произвольный момент согласования из карточки согласования КС

. Добавьте новую операцию редактирования в _Конструктор состояний_:
. Откройте _Конструктор состояний_.
. Выберите вид _Согласование КС_.
. Добавьте новую операцию редактирования: Interrupt the current stage (Прекратить текущий этап).
. Разрешите добавленную операцию для состояния “Запущено”.
. Сохраните.
. Разрешите новую операцию в _Конструкторе ролей_:
. Откройте _Конструктор ролей_.
. Выберите вид _Согласование КС_.
. Разрешите операцию “Прекратить текущий этап” роли “Инициатор” в состоянии “Запущено”.
. Сохраните.
. Добавьте кнопку, прекращающую текущей этап, в разметку карточки _Согласование КС_:
. Откройте _Конструктор разметок_.
. Выберите разметку “Инициатор управление”.
. Откройте настройки ленты.
. Добавьте новую кнопку InterruptCurrentStage (Прекратить текущий этап) в группу “Управление”. В качестве иконки для кнопки можно выбрать иконку Interrupt_stage.png (в приложенном архиве).
. Привяжите к кнопке операцию “Прекратить текущий этап”.
. Добавьте для кнопки обработчик события ItemClick, с вызовом единственного метода: `this.ReconcileHelper.InterruptCurrentStages_Click()`.
. Скомпилируйте скрипт и сохраните изменения в разметке.