= Исправление доступности операции редактирования маршрута в карточке согласования КС

. Разрешите операцию “Кнопки редактирования маршрута” в _Конструкторе состояний_:
. Откройте _Конструктор состояний_.
. Выберите вид _Согласование КС_.
. Разрешить операцию “Кнопки редактирования маршрута” в состояниях “Подготавливается”, “Запущено” и “Приостановлено”.
. Сохраните.
. Разрешите операцию “Кнопки редактирования маршрута” в _Конструкторе ролей_:

. Откройте _Конструктор ролей_.
. Выберите вид _Согласование КС_.
. Разрешите роли “Инициатор” операцию “Кнопки редактирования маршрута” для состояний “Подготавливается”, “Запущено” и “Приостановлено”.
. Сохраните.
. Привяжите операцию “Кнопки редактирования маршрута” к элементу управления “Редактор этапов”:

. Откройте _Конструктор разметок_.
. Выберите вид _Согласование КС_.
. Откройте разметку “Инициатор управление”.
. В настройках элемента управления “Редактор этапов” (вкладка “Состав маршрута”) укажите операцию редактирования – “Кнопки редактирования маршрута”.
. Повторите привязку операции редактирования для разметки “Инициатор подготовка”.
. Сохраните.