= Отображение делегатов в элементе управления "Дерево исполнения"

. Открыть Конструктор разметок, выбрать тип карточек “Задание”, вид – “На исполнение” (подвид “Задание УД”).

. Поочерёдно в разметках “Контроль”, “Завершено” и “Исполнение” на вкладке “Дерево исполнения” в свойствах элемента управления “Дерево исполнения” в группе Поведение/Столбцы установить флаг для значения “Делегировал”.

. Выполнить сохранение Конструктора разметок.

. Для вида задания “На ознакомление” настройка выполняется аналогичным образом, необходимо повторить шаги 1-3.

. Для всех видов, дочерних к “Задание КС”, шаги 1-3 выполняется для разметок “Базовая” и “Делегирование”.

. Для видов карточек “Группа заданий” и “Группа заданий УД” дополнительные настройки не требуются, столбец “Делегировал” появляется автоматически на вкладке “Задания”. 

. Для вида “Согласование КС” карточек типа “Согласование” необходимо выполнить шаги 1-3 для разметки “Инициатор управление”, выполнив указанные действия для элемента управления, расположенного на вкладке “Задания”.

. Во всех документах УД шаги 1-3 выполняются на вкладке “Задания”.