= Возможные ошибки при обновлении

== Ошибка уникальности операций

Возможна ситуация, когда при обновлении БД {dv} будет получена ошибка и в логе сервера содержится следующая информация:

----
Method name: StorageServer.RowSetData
                Param1: 23c42136-0ee3-e211-905a-005056c00008
                Param2: 20d21193-9f7f-4b62-8d69-272e78e1d6a8
                Param3: c81fa07c-2328-4821-b453-ae5959bf8fae
                Stack trace:    at {dv}.Platform.StorageServer.StorageServer.RetryIfFail(Action requestOperation)
   at {dv}.Platform.StorageServer.StorageServer.RowSetData(Guid sessionId, Guid sectionId, Guid rowId, String rowData)
    ProcessId=3320
    DateTime=2013-07-02T15:55:09.0269569+04:00
StorageServerRuntime Error: 0 :
Violation of UNIQUE KEY constraint 'dvsys_refstates_operations_uc_section_defaultname'. Cannot insert duplicate key in object 'dbo.dvtable_{a5d22d25-435d-4f08-bf02-b4e9f778709f}'. The duplicate key value is (Set controller, 9395e682-2b5a-4ee0-84c8-1ff5b4bf5217, <NULL>).
The statement has been terminated.
----

Данная ошибка указывает на наличие дубликата встроенной операции приложения "Управление документами".

Для исправления ошибки выполните следующие действия:

. Определите вид карточек с ошибкой.

Идентификатор вида указан в тексте ошибки в сообщении `The duplicate key value is (Set controller, 9395e682-2b5a-4ee0-84c8-1ff5b4bf5217, &lt;NULL&gt;)`.

Обратите внимание на первые два параметра:

* "Set controller" -- название операции;

* "9395e682-2b5a-4ee0-84c8-1ff5b4bf5217" -- идентификатор вида, к которому привязана операция.

. Выполните скрипт в БД {dv}:

`sql
SELECT [RowID] FROM [dbo].[dvtable_{a5d22d25-435d-4f08-bf02-b4e9f778709f}] Operations WHERE [DefaultName] = &#39;Set controller&#39; and [ParentRowID] = &#39;{ИД вида}&#39;
`

Вместо `ИД вида` укажите идентификатор вида, полученный на шаге 1.

В поле RowID будет содержаться идентификатор строки операции, которая вызывает ошибку.

. Выполните скрипт для удаления дубликата операции:

`sql
DELETE [dbo].[dvtable_{a5d22d25-435d-4f08-bf02-b4e9f778709f}] WHERE RowID = &#39;{ИД из поля RowID}&#39;
`

Похожие ошибки следует исправить аналогичным способом.

Если в измененном Решении настроен доступ к элементам управления с использованием встроенных операций обновляемой версии Управления документами, то необходимо перенастроить доступ с использованием операций Управления документами новой версии.