= Ключевые изменения в версии 5.5

== Модульность

{pl} {dv} 5.4 представляла собой монолит, который включал сервер и клиент {dv}, модули {ad}, {ud}, {bo} и т.д. Дополнительные Модули и Приложения устанавливались отдельно.

.В {dv} 5.5 данный монолит был разделён на отдельные модули:
* {pl}.
* {bo}.
* {ud}.
* Управление процессами.
* {ad}.
* {wincl}.
* Делопроизводство 4.5.

В {dv} 5.5 каждый модуль обладает собственным пакетом установки и комплектом документации.

== Сателлитные базы данных

В новой версии появилась возможность использовать отдельные базы данных для хранения архивных карточек, журналов и некоторых системных таблиц.

== Поддержка внешних хранилищ файлов

В {dv} 5.5 содержимое файлов может быть вытеснено из основной БД {dv} в отдельную БД, на файловую систему или в иное хранилище.

== Поддержка СУБД PostgreSQL

В качестве СУБД теперь может использоваться PostgreSQL.

== Хранение расширенных метаданных в БД

.В новой версии изменился способ хранения расширенных метаданных в БД:
* Поля сохраняются в основных таблицах секций. Раньше использовались extended-секции.
* Для секций создаются таблицы со стандартными секционными названиями -- без суффикса *_extended*.

Данное изменение не затрагивает способ хранения динамических метаданных.

== Обновления модулей без полного обновления БД

Реализован механизм обновления базовых модулей {dv} ({pl}, {bo} и др.), значительно ускоряющий процесс обновления БД. Если у модуля изменились только программные компоненты, но не изменилась библиотека карточек, при его обновлении библиотека карточек повторно загружаться не будет.
