= Ключевые изменения в версии 5.5

== Модульность

Платформа {dv} 5.4 представляла собой монолит, который включал сервер и клиент {dv}, модули Конструктор согласований, Управление документами, Базовые объекты и т.д. Отдельно устанавливались дополнительные Модули и Приложения.

В {dv} 5.5 данный монолит был разделён на отдельные модули:

* Платформа,

* Базовые объекты,

* Управление документами,

* Управление процессами,

* Конструктор согласований,

* Windows-клиент,

* Делопроизводство 4.5.

Каждый модуль обладает собственным пакетом установки и комплектом документации.

== Сателлитные базы данных

В новой версии появилась возможность использовать для хранения архивных карточек, журналов и некоторых системных таблиц отдельные базы данных.

== Поддержка внешних хранилищ файлов

В {dv} 5.5 содержимое файлов может быть вытеснено из основной БД {dv} в отдельную БД, на файловую систему или в иное хранилище.

== Поддержка СУБД PostgreSQL

В качестве СУБД теперь может использоваться PostgreSQL.

== Хранение расширенных метаданных в БД

В новой версии изменился способ хранения расширенных метаданных в БД:

* поля сохраняются в основных таблицах секций – раньше использовались extended-секции;
* для секций создаются таблицы со стандартными секционными названиями - без суффикса "_extended".

Данное изменение не затрагивает способ хранения динамических метаданных.

== Обновления модулей без полного обновления БД

Реализован механизм обновления базовых модулей {dv} (Платформа, Базовые объекты и др.), значительно ускоряющий процесс обновления БД: если у модуля изменились только программные компоненты, но не изменилась библиотека карточек, при его обновлении библиотека карточек повторно загружаться не будет.