= Перенос архивных карточек

В {dv} 5.5 появилась возможность хранить данные архивных карточек в отдельной БД (в 5.4 архивные карточки могли храниться только в БД {dv}). Решение об использовании отдельной БД (в терминах {dv} – _сателлитная БД_) для хранения архивных карточек принимается при первоначальной настройке {dv} 5.5 (на этапе настройки базы данных). *После завершения настройки БД изменить способ хранения архивных данных будет нельзя.*

По умолчанию использование сателлитной БД для хранения архивных карточек ОТКЛЮЧЕНО – архивные карточки будут храниться в основной БД {dv} (как в {dv} 5.4).

Если планируется использовать новую возможность хранения архивных карточек в сателлитной БД, перед обновлением до версии 5.5 самостоятельно *извлеките из архива все карточки* (карточки с признаком "Архивная"). Для извлечения можно использовать программу Навигатор/РМА или функции API {dv}. Для получения списка архивных карточек обратитесь к таблице "dvsys_instances_archive" базы данных {dv}. Если при установке {dv} 5.5 будет ВКЛЮЧЕНО хранение архивных карточек в сателлитной БД, *карточки, которые не были извлечены из архива, станут недоступны* (для стандартных способов работы с данными). После установки и настройки {dv} 5.5 извлеченные из карточки можно будет поместить обратно в архив.

Если использовать сателлитную БД для хранения архивных карточек не планируется, выполнять указанные выше действия не нужно.