= Перенос загружаемых данных приложений {dv}

При обновлении БД {dv} библиотеки карточек Модулей и Приложений будут перезагружены. Если для {dv} 5.4 была разработана собственная библиотека карточек, её нужно будет также загрузить:

* Если для загрузки библиотеки карточек было разработано загружающее её https://www.{dv}.com/docs/DeveloperManual/index.html#DV5_NetstatSolutionSample/Concepts/CreateSnapIn.html[расширение Консоли настройки {dv}] – установите расширение после обновление БД до версии 5.5.

* Если библиотека карточек загружалась с помощью CardManager:

. Создайте новую папку в каталоге `C:\Program Files (x86)\{dv}\Platform\5.5\Tools\Database`. Например, создайте папку `MyCarLib`.

. Скопируйте в созданную папку (`C:\Program Files (x86)\{dv}\Platform\5.5\Tools\Database\MyCarLib`) файлы библиотеки карточек.

. Создайте в данной папке новый файл с названием `Install.xml` и следующим содержимым:

`xml
 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
 &lt;SqlPackage&gt;
 	&lt;SqlFile&gt;MyOwnCardLib.xml&lt;/SqlFile&gt;
 &lt;/SqlPackage&gt;
`

Данная библиотека карточек станет доступна для загрузки при обновлении БД {dv}.

____

Вариант с использованием `Install.xml` является предпочтительным в {dv} 5.5. Если библиотека карточек загружалась с помощью расширения Консоли настройки {dv}, рекомендуется изменить реализацию на использование `Install.xml`. Расширение Консоли настройки необходимо сохранить, если кроме библиотеки карточек оно используется для загрузки других данных Модуля/Приложения, например: бизнес-процессов, настроек справочников, карточек и пр.

____