= Обновление компонентов собственных решений

. В {dv} были обновлены компоненты DevExpress с версии 2013 до версии 2017 (17.2). Если в Решении использовались собственные компоненты, скомпилированные с явной зависимостью от библиотек DevExpress 2013, необходимо перекомпилировать их с использованием новой версии DevExpress (2017). Также могут потребоваться другие доработки, если в собственном коде использовалось API DevExpress.
+
. В {dv} 5.5 были обновлены собственные компоненты {dv}. Перекомпилируйте свои проекты, в которых есть зависимости от сборок {dv}.
+
. В новой версии {dv} изменился способ хранения расширенных метаданных в БД: теперь данные хранятся в основных таблицах секций, а не в отдельных "extended"-таблицах. При обновления системы стандартным образом все существующие данные из "extended"-таблиц будут перенесены в основные таблицы секций, а сами "extended"-таблицы переименованы в `dvtable_\{ID-секции}_extended_old_data`.
+
После обновления системы необходимо изменить код скриптов, напрямую обращающихся к "extended"-таблицам в БД, если такие функции были реализованы в Решении, например, для расчёта ролевой модели безопасности. К примеру, если существующий скрипт содержал обращение к таблице `dvtable_\{3997861d-4ff5-496a-b8a2-d16617de91d7}_extended`, теперь нужно обращаться к таблице `dvtable_\{3997861d-4ff5-496a-b8a2-d16617de91d7}`.
+
NOTE: Данное изменение не затрагивает динамические метаданные*. Скрипты, работающие с таблицами динамических секций и полей, изменять *не нужно*.
+
. Изменился цикл жизни серверного расширения: теперь на каждое обращение к расширению создается новый экземпляр, а затем уничтожается. Это может потребовать изменить код серверного расширения, если расширение сохраняет свое состояние между вызовами.
+
. Изменилось описание расширенных отчетов в схеме библиотеки карточек (теперь указывается тип файла отчета, задается описание колонок результирующей выборки и др.). Это может потребовать повторного формирования и загрузки собственных отчетов.
