= Перенос загружаемых данных приложений {dv}

При обновлении БД {dv} библиотеки карточек Модулей и Приложений будут перезагружены. Если для {dv} 5.4 была разработана собственная библиотека карточек, её нужно будет также загрузить:

* Если для загрузки библиотеки карточек было разработано загружающее её (см. руководство разработчика, раздел "xref:programmer:samples:solution/snap-in/new-snap-in.adoc[]"), установите расширение после обновления БД до версии 5.5.
* Если библиотека карточек загружалась с помощью CardManager:
+
.. Создайте новую папку в каталоге `C:\Program Files (x86)\Docsvision\Platform\Tools\Database`. Например, создайте папку `MyCarLib`.
+
.. Скопируйте в созданную папку (`C:\Program Files (x86)\Docsvision\Platform\Tools\Database\MyCarLib`) файлы библиотеки карточек.
+
.. Создайте в данной папке новый файл с названием `Install.xml` и следующим содержимым:
+
[source,xml]
----
<xml version="1.0"; encoding="UTF-8">
<SqlPackage>
    <SqlFile>MyOwnCardLib.xml</SqlFile> <.>
</SqlPackage>
----
<.> Вместо `MyOwnCardLib.xml` укажите собственное название файла со схемой библиотеки карточек.
+
Данная библиотека карточек станет доступна для загрузки при обновлении БД {dv}.
+
[NOTE]
====
Вариант с использованием `Install.xml` является предпочтительным в {dv} 5.5. Если библиотека карточек загружалась с помощью расширения Консоли настройки {dv}, рекомендуется изменить реализацию на использование `Install.xml`. Расширение Консоли настройки необходимо сохранить, если кроме библиотеки карточек оно используется для загрузки других данных Модуля/Приложения, например: бизнес-процессов, настроек справочников, карточек и пр.
====
